### ISSUE TITLE
CoolDown TBC latest version

### ISSUE THREAD

**Issue by Macumbafeh** [wereHamster/coolDown#2]
Hey ! 

Do you have the latest Version of TBC anywhere, even if you don't play anymore wow... i hope you kept it.

ty !

**Comment by wereHamster** [comment]
Find out what the interface version for TBC is and then pick the appropriate version from the [history](https://github.com/wereHamster/coolDown/commits/master).

**Comment by Macumbafeh** [comment]
Thanks you so much ! 
Didn't know this trick on github :0 Awesome !
And btw thank you for all your great addons
